# Generated by Django 4.0.5 on 2022-08-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_userprofile'),
        ('users', '0003_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='api.recipe'),
        ),
    ]
