# Generated by Django 4.1.7 on 2023-03-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_ar', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('device_version', models.CharField(default='', max_length=100)),
                ('error', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ar', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_ar', models.CharField(max_length=50, null=True)),
                ('imageURL', models.ImageField(null=True, upload_to='recipes')),
                ('isVegetarian', models.BooleanField(default=False)),
                ('time_taken', models.IntegerField(null=True)),
                ('calories', models.IntegerField(null=True)),
                ('video', models.CharField(max_length=500, null=True)),
                ('ingridents', models.TextField(default='')),
                ('ingridents_en', models.TextField(default='', null=True)),
                ('ingridents_ar', models.TextField(default='', null=True)),
                ('directions', models.TextField(default='')),
                ('directions_en', models.TextField(default='', null=True)),
                ('directions_ar', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('difficulty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.difficulty')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
