# Generated by Django 4.0.5 on 2022-08-03 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('name_in_arabic', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_in_arabic', models.CharField(default='', max_length=50)),
                ('imageURL', models.ImageField(null=True, upload_to='recipes')),
                ('diff', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
                ('time_taken', models.IntegerField(null=True)),
                ('calories', models.IntegerField(null=True)),
                ('video', models.CharField(max_length=500, null=True)),
                ('video_in_arabic', models.CharField(max_length=500, null=True)),
                ('ingridents', models.TextField(default='')),
                ('ingridents_in_arabic', models.TextField(default='')),
                ('directions', models.TextField(default='')),
                ('directions_in_arabic', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='BreakfastModel',
        ),
        migrations.DeleteModel(
            name='Difficulty',
        ),
        migrations.DeleteModel(
            name='DinnerModel',
        ),
        migrations.DeleteModel(
            name='LunchModel',
        ),
        migrations.DeleteModel(
            name='RecipeModel',
        ),
        migrations.DeleteModel(
            name='RecipesTypes',
        ),
        migrations.DeleteModel(
            name='SnacksModel',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isVegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
    ]
