# Generated by Django 4.1.7 on 2023-03-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(null=True, upload_to='patients'),
        ),
    ]
