# Generated by Django 4.0.5 on 2022-08-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_recipe_delete_breakfastmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
