# Generated by Django 4.1.7 on 2023-03-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='image',
            field=models.ImageField(null=True, upload_to='difficulties'),
        ),
    ]
