# Generated by Django 4.0.5 on 2022-08-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='isVegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
